name: Build Optimized Whisper.cpp for CoreELEC

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make cmake g++-aarch64-linux-gnu libopenblas-dev

      - name: Clone whisper.cpp repository
        uses: actions/checkout@v4
        with:
          repository: ggerganov/whisper.cpp
          submodules: true

      - name: Create Toolchain File
        run: |
          echo 'set(CMAKE_SYSTEM_NAME Linux)' > aarch64-toolchain.cmake
          echo 'set(CMAKE_SYSTEM_PROCESSOR aarch64)' >> aarch64-toolchain.cmake
          echo 'set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)' >> aarch64-toolchain.cmake
          echo 'set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)' >> aarch64-toolchain.cmake

      - name: Compile with CMake, OpenBLAS and Static Linking
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=../aarch64-toolchain.cmake \
            -DCMAKE_CXX_FLAGS="-O3 -mtune=cortex-a53 -static" \
            -DWHISPER_OPENBLAS=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DWHISPER_BUILD_EXAMPLES=OFF # Отключаем сборку лишних примеров

          # --- ИЗМЕНЕНИЕ ЗДЕСЬ: Собираем и библиотеку, и главный исполняемый файл ---
          make -j$(nproc) whisper main

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: optimized-whisper-main
          # --- ИЗМЕНЕНИЕ ЗДЕСЬ: Упаковываем правильный файл из правильного места ---
          path: build/bin/main
