name: Build LEGACY Statically Optimized Whisper.cpp for CoreELEC

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make g++-aarch64-linux-gnu

      - name: Clone whisper.cpp LEGACY repository
        uses: actions/checkout@v4
        with:
          repository: ggerganov/whisper.cpp
          ref: v1.4.2
          path: whisper.cpp

      - name: Patch Makefile to remove test run
        working-directory: whisper.cpp
        # --- ГЛАВНОЕ ИСПРАВЛЕНИЕ: Удаляем тестовый запуск из Makefile ---
        run: sed -i '/^\.\/main -h/d' Makefile

      - name: Compile Statically with LEGACY Makefile
        working-directory: whisper.cpp
        run: |
          make -j$(nproc) main \
            CC="aarch64-linux-gnu-gcc" \
            CXX="aarch64-linux-gnu-g++" \
            CFLAGS="-I. -O3 -DNDEBUG -std=c11 -fPIC -pthread -mtune=cortex-a53" \
            CXXFLAGS="-I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread -mtune=cortex-a53" \
            LDFLAGS="-static"

      - name: Check file size and type
        run: |
          echo "Checking built file:"
          ls -lh whisper.cpp/main
          file whisper.cpp/main

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: optimized-whisper-static-main-LEGACY-v142
          path: whisper.cpp/main
          
