name: Build Statically Optimized Whisper.cpp for CoreELEC

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git g++-aarch64-linux-gnu

      - name: Clone whisper.cpp STABLE repository
        uses: actions/checkout@v4
        with:
          repository: ggml-org/whisper.cpp
          ref: v1.6.0
          submodules: true
          path: whisper.cpp

      - name: Compile Statically (Manual Method)
        working-directory: whisper.cpp
        run: |
          # --- Ручная компиляция для полного контроля ---
          aarch64-linux-gnu-g++ \
            -I. -I./examples \
            -O3 -mtune=cortex-a53 -static \
            -pthread \
            -o main \
            examples/main/main.cpp \
            examples/common.cpp \
            examples/common-ggml.cpp \
            examples/grammar-parser.cpp \
            whisper.cpp \
            ggml.c ggml-alloc.c ggml-backend.c ggml-quants.c

      - name: Check file size and type
        run: |
          echo "Checking built file:"
          ls -lh whisper.cpp/main
          file whisper.cpp/main
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: optimized-whisper-static-main
          path: whisper.cpp/main
