name: Build Statically Optimized Whisper.cpp for CoreELEC

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make g++-aarch64-linux-gnu

      - name: Clone whisper.cpp STABLE repository
        uses: actions/checkout@v4
        with:
          repository: ggml-org/whisper.cpp
          ref: v1.6.0
          submodules: true

      - name: Compile Statically with Makefile
        working-directory: whisper.cpp
        run: |
          # Используем Makefile напрямую, игнорируя CMake
          # CROSS_COMPILE=aarch64-linux-gnu-: Указываем префикс для кросс-компилятора
          # CFLAGS="-O3 -mtune=cortex-a53 -static": Передаем все флаги
          make -j$(nproc) main \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CFLAGS="-O3 -mtune=cortex-a53 -static"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: optimized-whisper-static-main
          path: whisper.cpp/main
