name: Build Optimized Whisper.cpp for CoreELEC (No BLAS)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          # --- ИЗМЕНЕНИЕ: Убрали libopenblas-dev ---
          sudo apt-get install -y git make cmake g++-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: Clone whisper.cpp STABLE repository
        uses: actions/checkout@v4
        with:
          repository: ggml-org/whisper.cpp
          ref: v1.6.0
          submodules: true

      - name: Create Toolchain File
        run: |
          echo 'set(CMAKE_SYSTEM_NAME Linux)' > aarch64-toolchain.cmake
          echo 'set(CMAKE_SYSTEM_PROCESSOR aarch64)' >> aarch64-toolchain.cmake
          echo 'set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)' >> aarch64-toolchain.cmake
          echo 'set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)' >> aarch64-toolchain.cmake

      - name: Compile with CMake Optimizations
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=../aarch64-toolchain.cmake \
            -DCMAKE_CXX_FLAGS="-O3 -mtune=cortex-a53" \
            # --- ИЗМЕНЕНИЕ: Убрали флаги OpenBLAS и статической линковки ---
            -DWHISPER_BUILD_TESTS=OFF
          make -j$(nproc) main

      - name: Package Executable and Dependencies
        run: |
          mkdir package
          cp build/bin/main package/
          # Запускаем ldd, чтобы упаковать только базовые системные библиотеки (например, libstdc++)
          aarch64-linux-gnu-ldd build/bin/main | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp '{}' package/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: optimized-whisper-package-no-blas
          path: package
