name: Build Statically Optimized Whisper.cpp for CoreELEC

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make g++-aarch64-linux-gnu

      - name: Clone whisper.cpp STABLE repository
        uses: actions/checkout@v4
        with:
          repository: ggml-org/whisper.cpp
          # --- ИЗМЕНЕНИЕ: Берем более старую, но очень стабильную версию ---
          ref: v1.5.4
          path: whisper.cpp

      - name: Compile Statically with Makefile
        working-directory: whisper.cpp
        run: |
          # --- Используем самый простой и надежный метод ---
          make -j$(nproc) main \
            CC="aarch64-linux-gnu-gcc" \
            CXX="aarch64-linux-gnu-g++"

      - name: Check file size and type
        run: |
          echo "Checking built file:"
          ls -lh whisper.cpp/main
          file whisper.cpp/main

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: optimized-whisper-static-main-v154
          path: whisper.cpp/main
