# Имя нашего "рецепта"
name: Build Optimized Whisper.cpp for CoreELEC

# Триггер: запускать сборку при каждом коммите (сохранении) в основную ветку
on:
  push:
    branches:
      - main # Если ваша основная ветка называется 'master', измените 'main' на 'master'

jobs:
  build:
    # Запускать на самой свежей версии Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Установка необходимых инструментов
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make g++-aarch64-linux-gnu libopenblas-dev

      # Шаг 2: Скачиваем исходный код whisper.cpp
      - name: Clone whisper.cpp repository
        run: git clone https://github.com/ggerganov/whisper.cpp.git

      # Шаг 3: Компиляция с максимальной оптимизацией (ИСПРАВЛЕНО)
      - name: Compile with OpenBLAS and Optimizations
        working-directory: whisper.cpp
        run: |
          # Запускаем сборку с правильными флагами и правильной целью 'main'
          # WHISPER_OPENBLAS=1: Включаем поддержку OpenBLAS
          # CXX=aarch64-linux-gnu-g++: Указываем кросс-компилятор
          # CXXFLAGS: Флаги оптимизации под ваш процессор
          WHISPER_OPENBLAS=1 make -j$(nproc) main \
            CXX=aarch64-linux-gnu-g++ \
            CXXFLAGS="-O3 -mtune=cortex-a53 -mfpu=neon-fp-armv8"

      # Шаг 4: Упаковываем готовый файл в артефакт
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: optimized-whisper-main
          path: whisper.cpp/main
