name: Build Optimized Whisper.cpp for CoreELEC

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make cmake g++-aarch64-linux-gnu libopenblas-dev

      - name: Clone whisper.cpp repository
        uses: actions/checkout@v4
        with:
          repository: ggml-org/whisper.cpp
          submodules: true

      - name: Compile with CMake and OpenBLAS
        run: |
          mkdir build && cd build
          # Собираем обычный, динамический, но оптимизированный билд
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=../aarch64-toolchain.cmake \
            -DCMAKE_CXX_FLAGS="-O3 -mtune=cortex-a53" \
            -DWHISPER_OPENBLAS=ON \
            -DWHISPER_BUILD_TESTS=OFF
          make -j$(nproc) main

      - name: Package Executable and Dependencies
        run: |
          # Создаем папку для нашего пакета
          mkdir package
          # Копируем туда наш движок
          cp build/bin/main package/
          # Находим все нужные ему библиотеки и копируем их туда же
          aarch64-linux-gnu-ldd build/bin/main | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp '{}' package/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: optimized-whisper-package
          path: package
